version: '3.8'

services:
  # Service MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studlearn
      # Supprimez les variables MYSQL_USER et MYSQL_PASSWORD pour éviter les erreurs.
    networks:
      - mysql-phpmyadmin

  # Application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studlearn
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: studlearn
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html
    networks:
      - mysql-phpmyadmin

  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

volumes:
  db_data:

networks:
  mysql-phpmyadmin:
