version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studlearn
      MYSQL_USER: root  # Ajout de la variable utilisateur
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin  # Correction de l'image pour phpMyAdmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password  # Correction de la variable d'environnement
    networks:
      - mysql-phpmyadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studlearn
    ports:
      - "8000:8000"
    depends_on:
      - db  # Correction de la dépendance (mysql -> db)
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db  # Correction du host pour correspondre au service 'db'
      DB_PORT: 3306
      DB_DATABASE: studlearn  # Assurez-vous que cela correspond à MYSQL_DATABASE
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
