version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studlearn
    networks:
      - mysql-phpmyadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studlearn
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: studlearn
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html
    command: sh -c "sleep 20 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

volumes:
  db_data:

networks:
  mysql-phpmyadmin:
