version: '3.8'

services:
  # Service MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: studlearn
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password

  # Service de l'application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studlearn
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: studlearn
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html

volumes:
  db_data:
