version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studlearn
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=studlearn
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data:
